---
# Test a basic run.
- hosts: "{{ test_hostname }}"
  sudo: yes
  roles:
    - role: cpufrequtils

# Test cpufreq_enable.
- hosts: "{{ test_hostname }}"
  sudo: yes
  roles:
    - role: cpufrequtils
      cpufreq_enable: yes
  post_tasks:
    - name: test cpufreq_enable
      shell: . /etc/default/cpufrequtils && [ "$ENABLE" = "true" ] || exit 1

# Test cpufreq_governor.
- hosts: "{{ test_hostname }}"
  sudo: yes
  roles:
    - role: cpufrequtils
      cpufreq_governor: "performance"
  post_tasks:
    - name: test cpufreq_governor
      shell: . /etc/default/cpufrequtils && [ "$GOVERNOR" = "performance" ] || exit 1

# Test cpufreq_max_speed.
- hosts: "{{ test_hostname }}"
  sudo: yes
  roles:
    - role: cpufrequtils
      cpufreq_max_speed: 1234
  post_tasks:
    - name: test cpufreq_max_speed
      shell: . /etc/default/cpufrequtils && [ "$MAX_SPEED" = "1234" ] || exit 1

# Test cpufreq_min_speed.
- hosts: "{{ test_hostname }}"
  sudo: yes
  roles:
    - role: cpufrequtils
      cpufreq_min_speed: 4321
  post_tasks:
    - name: test cpufreq_min_speed
      shell: . /etc/default/cpufrequtils && [ "$MIN_SPEED" = "4321" ] || exit 1
